/**
 * ApiTxt OTP Service
 *
 * Wraps the GET /api/sendOTP endpoint from apitxt.com.
 * Reads credentials from env vars:
 *   APITXT_AUTH_KEY      — Your unique API authentication key
 *   APITXT_TEMPLATE_ID   — (Optional) Your SMS template ID from the dashboard.
 *                          If omitted, the system default SMS OTP config is used.
 *
 * The OTP value is generated by the caller; this module only delivers it.
 * Supports SMS (default), WhatsApp, and Voice channels.
 */

const BASE_URL = "https://apitxt.com/api/sendOTP";

/**
 * normalizeIndianPhone(phone)
 *
 * ApiTxt expects the full number with country code, no leading +.
 * Accepts any of these formats and returns "91XXXXXXXXXX":
 *   "9876543210"        → "919876543210"
 *   "919876543210"      → "919876543210"  (already correct)
 *   "+919876543210"     → "919876543210"
 *   "09876543210"       → "919876543210"
 *
 * Throws if the result doesn't look like a valid 10-digit Indian mobile.
 */
const normalizeIndianPhone = (phone) => {
  let digits = phone.replace(/[\s\-]/g, "");

  // Strip leading +
  if (digits.startsWith("+")) digits = digits.slice(1);

  // Strip leading 0 (trunk prefix)
  if (digits.startsWith("0")) digits = digits.slice(1);

  // Strip country code 91 if present and followed by 10 digits
  if (digits.startsWith("91") && digits.length === 12) {
    digits = digits.slice(2);
  }

  if (!/^[6-9]\d{9}$/.test(digits)) {
    throw new Error(`Invalid Indian mobile number: "${phone}"`);
  }

  // ApiTxt auto-prepends 91 for 10-digit numbers, but passing the full
  // number is more explicit and avoids ambiguity.
  return `91${digits}`;
};

/**
 * sendOtpViaSms(phoneNumber, otp, options)
 *
 * @param {string} phoneNumber  Indian mobile — any common format accepted
 * @param {string} otp          The 4-6 digit OTP string to deliver
 * @param {object} [options]
 * @param {string} [options.channel='sms']  'sms' | 'whatsapp' | 'voice'
 * @returns {Promise<{ requestId: string, mobile: string, cost: number }>}
 * @throws  {Error} on non-2xx response, API-level failure, or network error
 */
export const sendOtpViaSms = async (phoneNumber, otp, options = {}) => {
  const authkey = process.env.APITXT_AUTH_KEY;

  if (!authkey) {
    throw new Error("APITXT_AUTH_KEY is not set in environment variables.");
  }

  const mobile = normalizeIndianPhone(phoneNumber);
  const channel = options.channel ?? "sms";

  const params = new URLSearchParams({
    authkey,
    mobile,
    otp: String(otp),
    channel,
  });

  // Attach optional SMS template ID if configured
  const templateId = process.env.APITXT_TEMPLATE_ID;
  if (templateId && channel === "sms") {
    params.set("template_id", templateId);
  }

  const response = await fetch(`${BASE_URL}?${params.toString()}`, {
    method: "GET",
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`ApiTxt HTTP error ${response.status}: ${errorText}`);
  }

  const data = await response.json();

  if (data.status !== "success") {
    throw new Error(`ApiTxt error: ${data.message ?? JSON.stringify(data)}`);
  }

  return {
    requestId: data.data?.request_id ?? null,
    mobile: data.data?.mobile ?? mobile,
    cost: data.data?.cost ?? null,
  };
};
