/**
 * StartMessaging OTP Service
 *
 * Wraps the POST /otp/send endpoint from api.startmessaging.com.
 * Reads credentials from env vars:
 *   START_MESSAGING_API_KEY      — X-API-Key header value
 *   START_MESSAGING_TEMPLATE_ID  — template ID (default: 0afbdeb0-785d-4dd0-bd48-365a182df276)
 *
 * The OTP value is generated by the caller; this module only delivers it.
 */

const BASE_URL = "https://api.startmessaging.com";

// Template ID from the StartMessaging docs (active "Your OTP is {{otp}}..." template)
const DEFAULT_TEMPLATE_ID = "0afbdeb0-785d-4dd0-bd48-365a182df276";

/**
 * normalizeIndianPhone(phone)
 *
 * Accepts any of these formats and returns "+91XXXXXXXXXX":
 *   "9876543210"        → "+919876543210"
 *   "919876543210"      → "+919876543210"
 *   "+919876543210"     → "+919876543210"  (already correct)
 *   "09876543210"       → "+919876543210"
 *
 * Throws if the result doesn't look like a valid 10-digit Indian mobile.
 */
const normalizeIndianPhone = (phone) => {
  // Strip all whitespace and dashes
  let digits = phone.replace(/[\s\-]/g, "");

  // Strip leading +
  if (digits.startsWith("+")) digits = digits.slice(1);

  // Strip leading 0 (trunk prefix)
  if (digits.startsWith("0")) digits = digits.slice(1);

  // Strip country code 91 if present and followed by 10 digits
  if (digits.startsWith("91") && digits.length === 12) {
    digits = digits.slice(2);
  }

  if (!/^[6-9]\d{9}$/.test(digits)) {
    throw new Error(`Invalid Indian mobile number: "${phone}"`);
  }

  return `+91${digits}`;
};

/**
 * sendOtpViaSms(phoneNumber, otp)
 *
 * @param {string} phoneNumber  Indian mobile — any common format accepted
 * @param {string} otp          The 4-6 digit OTP string to deliver
 * @returns {Promise<{ messageId: string }>}
 * @throws  {Error} on non-2xx response or network failure
 */
export const sendOtpViaSms = async (phoneNumber, otp) => {
  const normalized = normalizeIndianPhone(phoneNumber);
  const apiKey = process.env.START_MESSAGING_API_KEY;

  if (!apiKey) {
    throw new Error("START_MESSAGING_API_KEY is not set in environment variables.");
  }

  const templateId =
    process.env.START_MESSAGING_TEMPLATE_ID || DEFAULT_TEMPLATE_ID;

  const response = await fetch(`${BASE_URL}/otp/send`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-API-Key": apiKey,
    },
    body: JSON.stringify({
      phoneNumber: normalized,
      templateId,
      variables: { otp },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `StartMessaging API error ${response.status}: ${errorText}`
    );
  }

  const data = await response.json();

  // The API returns a message object; surface the ID for optional status polling
  return { messageId: data.id ?? data.messageId ?? null };
};
